### ISSUE TITLE
Input truncted

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [trezor/trezor-qrenc#4]
The input is always truncated on the last character.
This is desirable when the last character is a carriage return, but not otherwise.

**Comment by prusnak** [comment]
Are you talking about `test.c` or the library itself?

**Comment by prusnak** [comment]
I assume this is just about `test.c`, fixed in https://github.com/trezor/trezor-qrenc/commit/9344f23d869030fbe7261d3361862eaba12b9975

Library itself is OK.

Thanks!

**Comment by GeoffreyFrogeye** [comment]
I can confirm it works :)
Thanks a lot!
