### ISSUE TITLE
check.h file is missing...

### ISSUE THREAD

**Issue by denisdemaisbr** [trezor/trezor-qrenc#5]
**$ make**
gcc -o qr_encode.o -c qr_encode.c
gcc -o test.o -c test.c
gcc -O3 -g -W -Wall -Wextra -Wimplicit-function-declaration -Wredundant-decls -Wstrict-prototypes -Wundef -Wshadow -Wpointer-arith -Wformat -Wreturn-type -Wsign-compare -Wmultichar -Wformat-nonliteral -Winit-self -Wuninitialized -Wformat-security -DQR_MAX_VERSION=0 qr_encode.o test.o -o test
gcc -o tests.o -c tests.c
**tests.c:23:19: fatal error: check.h: No such file or directory**
compilation terminated.
**make: *** [Makefile:35: tests.o] Error 1**

**Comment by prusnak** [comment]
Install libcheck-dev or similar package on your system.
