### ISSUE TITLE
RAM is using too much, who can improve?

### ISSUE THREAD

**Issue by Asxin** [trezor/trezor-qrenc#7]
I use STM32F103 MCU to find that RAM has high usage when using large two-dimensional code. Can we improve the use of a very small number of RAM? For example, using a bit to represent a point？

**Comment by prusnak** [comment]
I would suggest trying a different QR Code implementation. I am thinking of dropping this code and replacing it with https://github.com/ricmoo/QRCode or https://github.com/tz1/qrduino or something similar with better attributes.
